### ISSUE TITLE
Add the ability of hiding values for certain inputs

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/metal-input-matrix#5]
Nowadays, the values of environment variables are available for anyone to see:

<img width="861" alt="screen shot 2016-10-28 at 9 48 02 am" src="https://cloud.githubusercontent.com/assets/398893/19814585/a6b3cf6c-9cf3-11e6-930d-2d6c73903b52.png">

We want to add a feature on the second input of each row to hide that value.

@ygorcosta and @mairatma, can you help us with that?

---

**State 1:** `<input type="password" readonly>`

<img width="291" alt="screen shot 2016-10-28 at 9 29 40 am" src="https://cloud.githubusercontent.com/assets/398893/19814432/03493222-9cf3-11e6-9a2d-95ae2115785b.png">

**State 2:** Hover button

<img width="294" alt="screen shot 2016-10-28 at 9 29 46 am" src="https://cloud.githubusercontent.com/assets/398893/19814433/034ccab8-9cf3-11e6-9b5d-7b565c0e0f1a.png">

**State 3:** `<input type="text">`

<img width="291" alt="screen shot 2016-10-28 at 9 29 55 am" src="https://cloud.githubusercontent.com/assets/398893/19814434/034d2b52-9cf3-11e6-8b70-4c73ea460db6.png">

**Comment by mairatma** [comment]
Seems like this should be another option in `fieldsConfig`, with the type of the input. By default we'd use `text`, but when this is set to `password` we can also add the button to show/hide the content.

This `readonly` attribute seems like another separate option though, otherwise people won't be able to have an editable password field, right?

**Comment by zenorocha** [comment]
Yeah, we can have these two options inside `fieldsConfig` and then the button listener is responsible of setting it.

**Comment by ygorcosta** [comment]
Hi, I added these states to westyle. You can check them here http://westyle.wedeploy.io/#section-forms

**Comment by ygorcosta** [comment]
@mairatma @zenorocha I created [this component ](https://github.com/ygorcosta/metal-toggle-password-input) to help us in this issue. can you review that?
