### ISSUE TITLE
Add syncFields callback method (metal components) for input matrix

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/metal-input-matrix#9]
- After submit environment variables using a form, duplicated inputs are not updating after change of number of fields.

Possible fix:
```
syncFields(val) {
     this.currentFields_ = val;
}
```

and  keep the current `created()`

**Comment by eduardolundgren** [comment]
Done here https://github.com/wedeploy/metal-input-matrix/commit/dc482f858af1afb648eb49dc391282eea67d85b4. Thanks.
